# need superuser permissions to build
sudo: required
services:
  - docker

before_install:
  - docker build -t missym2/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true missym2/docker-react npm run test

# for deploying on aws
deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-638751097140"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
